// export const asideMenus = {
// 	Home: {
// 		id: 'Home',
// 		text: '홈',
// 		path: '/',
// 		icon: 'Home',
// 		subMenu: null,
// 	},
// 	pay: {
// 		id: 'pay',
// 		text: '급여',
// 		path: 'pages/pay',
// 		icon: 'Payments',
// 		subMenu: null,
// 	},
// 	self_pay: {
// 		id: 'self_pay',
// 		text: '본인부담금',
// 		path: 'pages/self_pay',
// 		icon: 'AttachMoney',
// 		subMenu: null,
// 	},
// 	four_major_insurance: {
// 		id: 'four_major_insurance',
// 		text: '4대 보험',
// 		path: 'pages/four_major_insurance',
// 		icon: 'Assignment',
// 		subMenu: null,
// 	},
// 	account_details: {
// 		id: 'account_details',
// 		text: '계좌내역',
// 		path: 'pages/account_details',
// 		icon: 'AccountBalance',
// 		subMenu: null,
// 	},
// 	recipient: {
// 		id: 'recipient',
// 		text: '수급자',
// 		path: 'pages/recipient',
// 		icon: 'Person',
// 		subMenu: null,
// 	},
// 	caregiver: {
// 		id: 'caregiver',
// 		text: '요양보호사',
// 		path: 'pages/caregiver',
// 		icon: 'Person',
// 		subMenu: null,
// 	},
// 	tag_error: {
// 		id: 'tag_error',
// 		text: '기록지 / 태그오류',
// 		path: 'pages/tag_error',
// 		icon: 'AssignmentLate',
// 		subMenu: null,
// 	},
// 	modu_sign: {
// 		id: 'modu_sign',
// 		text: '모두싸인 계약목록',
// 		path: 'pages/modu_sign',
// 		icon: 'Assignment',
// 		subMenu: null,
// 	},
// 	contractor: {
// 		id: 'contractor',
// 		text: '계약대기자 / 자격증',
// 		path: 'pages/',
// 		icon: 'AssignmentInd',
// 		subMenu: null,
// 	},
// 	doc_management: {
// 		id: 'doc_management',
// 		text: '서류관리',
// 		path: 'pages/doc_management',
// 		icon: 'Archive',
// 		subMenu: null,
// 	},
// 	post_message: {
// 		id: 'post_message',
// 		text: '메시지 발송',
// 		path: 'pages/post_message',
// 		icon: 'Message',
// 		subMenu: null,
// 	},
// 	finance: {
// 		id: 'finance',
// 		text: '재무',
// 		path: 'pages/finance',
// 		icon: 'AttachMoney',
// 		subMenu: null,
// 	},
// };
export const asideMenus = {
	consult: {
		id: 'consult',
		text: '상담관리',
		path: 'pages/consult',
		icon: 'HeadsetMic',
		subMenu: null,
	},
	statistics: {
		id: 'statistics',
		text: '통계',
		path: 'pages/statistics',
		icon: 'BarChartFill',
		subMenu: null,
	},
	smile: {
		id: 'smail_call',
		text: '스마일콜',
		path: 'pages/smile',
		icon: 'PhoneVibrate',
		subMenu: null,
	},
	beneficiary_management: {
		id: 'beneficiary_management',
		text: '수급자 관리',
		path: 'pages/beneficiary',
		icon: 'Accessible',
		subMenu: null,
	},
	caregiver_management: {
		id: 'call',
		text: '요양보호사 관리',
		path: 'pages/caregiver',
		icon: 'Person',
		subMenu: null,
	},
};
